# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170301_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
