# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170301_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
