# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_issue_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='session',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
